### Importing Libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import save_model,load_model

### Importing Dataset

In [2]:
df = pd.read_csv("Clean Data.csv")
df.head()

ID Delivery_person_ID  Delivery_person_Age  Delivery_person_Ratings  \
0  0x4607     INDORES13DEL02                  37.0                      4.9   
1  0xb379     BANGRES18DEL02                  34.0                      4.5   
2  0x5d6d     BANGRES19DEL01                  23.0                      4.4   
3  0x7a6a    COIMBRES13DEL02                  38.0                      4.7   
4  0x70a2     CHENRES12DEL01                  32.0                      4.6   

   Restaurant_latitude  Restaurant_longitude  Delivery_location_latitude  \
0            22.745049             75.892471                   22.765049   
1            12.913041             77.683237                   13.043041   
2            12.914264             77.678400                   12.924264   
3            11.003669             76.976494                   11.053669   
4            12.972793             80.249982                   13.012793   

   Delivery_location_longitude  Order_Date Time_Orderd  ... Weatherconditions  \
0                    75.912471  19-03-2022    11:30:00  ...             Sunny   
1                    77.813237  25-03-2022    19:45:00  ...            Stormy   
2                    77.688400  19-03-2022    08:30:00  ...        Sandstorms   
3                    77.026494  05-04-2022    18:00:00  ...             Sunny   
4                    80.289982  26-03-2022    13:30:00  ...            Cloudy   

  Road_traffic_density Vehicle_condition  Type_of_order Type_of_vehicle  \
0                 High                 2          Snack      motorcycle   
1                  Jam                 2          Snack         scooter   
2                  Low                 0         Drinks      motorcycle   
3               Medium                 0         Buffet      motorcycle   
4                 High                 1          Snack         scooter   

  multiple_deliveries  Festival           City Time_taken(min)   Distance  
0                 0.0        No          Urban              24   3.025149  
1                 1.0        No  Metropolitian              33  20.183530  
2                 1.0        No          Urban              26   1.552758  
3                 1.0        No  Metropolitian              21   7.790401  
4                 1.0        No  Metropolitian              30   6.210138  

[5 rows x 21 columns]

### Feature Engineering

In [3]:
df.Weatherconditions.unique()

array(['Sunny', 'Stormy', 'Sandstorms', 'Cloudy', 'Fog', 'Windy'],
      dtype=object)

In [4]:
weather = dict()
for i in range(len(df.Weatherconditions.unique())):
    weather[df.Weatherconditions.unique()[i]] = i
weather

{'Sunny': 0, 'Stormy': 1, 'Sandstorms': 2, 'Cloudy': 3, 'Fog': 4, 'Windy': 5}

In [5]:
df['WeatherMapped'] = df['Weatherconditions'].map(weather)
df['WeatherMapped'].unique()

array([0, 1, 2, 3, 4, 5], dtype=int64)

In [6]:
df['Road_traffic_density'].unique()

array(['High', 'Jam', 'Low', 'Medium'], dtype=object)

In [7]:
traffic = {"Low":0,"Medium":1,"High":2,"Jam":3}
traffic

{'Low': 0, 'Medium': 1, 'High': 2, 'Jam': 3}

In [8]:
df['TrafficMapped'] = df['Road_traffic_density'].map(traffic)
df['TrafficMapped'].unique()

array([2, 3, 0, 1], dtype=int64)

In [9]:
print(df['Type_of_order'].unique())
order = dict()
for i in range(len(df['Type_of_order'].unique())):
    order[df['Type_of_order'].unique()[i]] = i
print(order)

['Snack' 'Drinks' 'Buffet' 'Meal']
{'Snack': 0, 'Drinks': 1, 'Buffet': 2, 'Meal': 3}


In [10]:
df['OrderTypeMapped'] = df['Type_of_order'].map(order)
df['OrderTypeMapped'].unique()

array([0, 1, 2, 3], dtype=int64)

In [11]:
print(df['Type_of_vehicle'].unique())
vehicle = dict()
for i in range(len(df['Type_of_vehicle'].unique())):
    vehicle[df['Type_of_vehicle'].unique()[i]] = i
print(vehicle)

['motorcycle' 'scooter' 'electric_scooter' 'bicycle']
{'motorcycle': 0, 'scooter': 1, 'electric_scooter': 2, 'bicycle': 3}


In [12]:
df['VehicleMapped'] = df['Type_of_vehicle'].map(vehicle)
df['VehicleMapped'].unique()

array([0, 1, 2, 3], dtype=int64)

In [13]:
print(df['Festival'].unique())
fest = dict()
for i in range(len(df['Festival'].unique())):
    fest[df['Festival'].unique()[i]] = i
print(fest)

['No' 'Yes']
{'No': 0, 'Yes': 1}


In [14]:
df['FestMapped'] = df['Festival'].map(fest)
df['FestMapped'].unique()

array([0, 1], dtype=int64)

In [15]:
print(df['City'].unique())
city = dict()
for i in range(len(df['City'].unique())):
    city[df['City'].unique()[i]] = i
print(city)

['Urban' 'Metropolitian' 'Semi-Urban']
{'Urban': 0, 'Metropolitian': 1, 'Semi-Urban': 2}


In [16]:
df['CityMapped'] = df['City'].map(city)
df['CityMapped'].unique()

array([0, 1, 2], dtype=int64)

In [17]:
df.head()

ID Delivery_person_ID  Delivery_person_Age  Delivery_person_Ratings  \
0  0x4607     INDORES13DEL02                  37.0                      4.9   
1  0xb379     BANGRES18DEL02                  34.0                      4.5   
2  0x5d6d     BANGRES19DEL01                  23.0                      4.4   
3  0x7a6a    COIMBRES13DEL02                  38.0                      4.7   
4  0x70a2     CHENRES12DEL01                  32.0                      4.6   

   Restaurant_latitude  Restaurant_longitude  Delivery_location_latitude  \
0            22.745049             75.892471                   22.765049   
1            12.913041             77.683237                   13.043041   
2            12.914264             77.678400                   12.924264   
3            11.003669             76.976494                   11.053669   
4            12.972793             80.249982                   13.012793   

   Delivery_location_longitude  Order_Date Time_Orderd  ... Festival  \
0                    75.912471  19-03-2022    11:30:00  ...       No   
1                    77.813237  25-03-2022    19:45:00  ...       No   
2                    77.688400  19-03-2022    08:30:00  ...       No   
3                    77.026494  05-04-2022    18:00:00  ...       No   
4                    80.289982  26-03-2022    13:30:00  ...       No   

            City Time_taken(min)   Distance WeatherMapped TrafficMapped  \
0          Urban              24   3.025149             0             2   
1  Metropolitian              33  20.183530             1             3   
2          Urban              26   1.552758             2             0   
3  Metropolitian              21   7.790401             0             1   
4  Metropolitian              30   6.210138             3             2   

   OrderTypeMapped VehicleMapped FestMapped  CityMapped  
0                0             0          0           0  
1                0             1          0           1  
2                1             0          0           0  
3                2             0          0           1  
4                0             1          0           1  

[5 rows x 27 columns]

### Feature Slicing & Splitting

In [18]:
df.columns

Index(['ID', 'Delivery_person_ID', 'Delivery_person_Age',
       'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 'Order_Date', 'Time_Orderd',
       'Time_Order_picked', 'Weatherconditions', 'Road_traffic_density',
       'Vehicle_condition', 'Type_of_order', 'Type_of_vehicle',
       'multiple_deliveries', 'Festival', 'City', 'Time_taken(min)',
       'Distance', 'WeatherMapped', 'TrafficMapped', 'OrderTypeMapped',
       'VehicleMapped', 'FestMapped', 'CityMapped'],
      dtype='object')

In [19]:
x = df[['Delivery_person_Age','Delivery_person_Ratings','Distance',
        'WeatherMapped', 'TrafficMapped', 'OrderTypeMapped',
        'VehicleMapped', 'FestMapped', 'CityMapped']]
y = df['Time_taken(min)']

In [20]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.15)

### Model Building

In [21]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout
from keras.layers import Activation

In [22]:
model = Sequential()

In [23]:
model.add(LSTM(128,return_sequences=True,input_shape=(x_train.shape[1],1)))
model.add(Dropout(0.25))
model.add(LSTM(64,return_sequences=False))
model.add(Dropout(0.25))
model.add(Dense(25))
model.add(Dropout(0.25))
model.add(Dense(1))

In [24]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 9, 128)            66560     
                                                                 
 dropout (Dropout)           (None, 9, 128)            0         
                                                                 
 lstm_1 (LSTM)               (None, 64)                49408     
                                                                 
 dropout_1 (Dropout)         (None, 64)                0         
                                                                 
 dense (Dense)               (None, 25)                1625      
                                                                 
 dropout_2 (Dropout)         (None, 25)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 2

In [25]:
model.compile(optimizer='adam', loss='mean_squared_error')
model.fit(x_train, y_train, batch_size=32, epochs=25)

Epoch 1/25
1212/1212 [==============================] - 45s 30ms/step - loss: 106.6041
Epoch 2/25
1212/1212 [==============================] - 29s 24ms/step - loss: 67.8233
Epoch 3/25
1212/1212 [==============================] - 28s 23ms/step - loss: 54.7903
Epoch 4/25
1212/1212 [==============================] - 28s 23ms/step - loss: 49.9646
Epoch 5/25
1212/1212 [==============================] - 28s 23ms/step - loss: 46.6006
Epoch 6/25
1212/1212 [==============================] - 28s 23ms/step - loss: 42.9397
Epoch 7/25
1212/1212 [==============================] - 28s 23ms/step - loss: 41.0391
Epoch 8/25
1212/1212 [==============================] - 28s 23ms/step - loss: 39.1019
Epoch 9/25
1212/1212 [==============================] - 28s 23ms/step - loss: 37.7925
Epoch 10/25
1212/1212 [==============================] - 29s 24ms/step - loss: 37.1206
Epoch 11/25
1212/1212 [==============================] - 31s 25ms/step - loss: 36.5873
Epoch 12/25
1212/1212 [============================

In [26]:
food_pred_json = model.to_json()

In [27]:
with open("Food Delivery Time Prediction.json","w") as json_file:
    json_file.write(food_pred_json)
model.save_weights("Model Weights.h5")
print("Saved Model")

Saved Model
